name:                composite-aeson
version:             0.5.5.0
synopsis:            JSON for Vinyl/Frames records
description:         Integration between Aeson and Vinyl/Frames records allowing records to be easily converted to JSON using automatic derivation, explicit formats, or a mix of both.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc
maintainer:          oss@confer.health
copyright:           2017 Confer Health, Inc.
category:            Records

dependencies:
  - base
  - aeson
  - aeson-better-errors
  - composite-base
  - containers
  - contravariant
  - generic-deriving
  - hashable
  - lens
  - mmorph
  - mtl
  - profunctors
  - scientific
  - tagged
  - template-haskell
  - text
  - time
  - unordered-containers
  - vector
  - vinyl

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-aeson-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - aeson-qq
      - composite-aeson
      - hspec
