name:                composite-swagger
version:             0.5.5.0
synopsis:            Swagger for Vinyl/Frames records
description:         Integration between Swagger and Vinyl/Frames records allowing easily derivable/explicit Swagger definitions for records.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc
maintainer:          oss@confer.health
copyright:           2017 Confer Health, Inc.
category:            Records

dependencies:
  - base
  - composite-base
  - insert-ordered-containers
  - lens
  - swagger2
  - template-haskell
  - text
  - vinyl

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-swagger-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - composite-aeson
      - composite-base
      - composite-swagger
      - hspec
